AWSTemplateFormatVersion: '2010-09-09'
Description: >-
  Project Helenium: CFN Template to create am IAM Role for AWS Config

Metadata:
  TemplateName: iam-role-stack.yaml
  TemplateType: IAM Role / IAM Policy
  Version: 1.0.0
  Owner: Subhamay Bhattacharyya
  ProjectName: Helenium
  Modification History:
    - 1.0.0  - Dec 26, 2023   -- Initial Version 
  Resources: 
    - IAM Role
    - IAM Policy Attached To The Role
  StepsToTest: |
    Manualy verify the Stack.
  StepsToCleanup: |
    Stack delete command

  AWS::CloudFormation::Interface:
    ParameterGroups:
    #################################### Project Name and Environment ##############################
    - Label: 
        default: 'Project And Environment:'
      Parameters: 
        - ProjectName
        - Environment
    #################################### GitHub Attributes #########################################
    - Label:
        default: "GitHub Attributes:"
      Parameters:
      - GitHubRef
      - GitHubURL
      - GitHubWFRunNumber
      - GitHubSHA
      - GitHubRepository
      - CiBuild
    ParameterLabels:
      ################################## Project Name and Environment ##############################
      ProjectName:
        default: "Project Name."
      Environment:
        default: "Environment Name."
      ################################## GitHub Attributes #########################################
      GitHubRef:
        default: "GitHub Ref"
      GitHubURL: 
        default: "GitHub repository URL"
      GitHubWFRunNumber:
        default: "GitHub Workflow Run Number."
      GitHubSHA: 
        default: "GitHub Workflow Run Number."
      GitHubRepository:
        default: "GitHub repository name."
      CiBuild:
        default: "Feature branch Ci Build"
Parameters:
  ################## Project Name and Environment ##################################################
  ProjectName:
    Default: project
    Description: 'The Project Name.'
    Type: String
    MinLength: 6
    MaxLength: 30
    AllowedPattern: '[a-z]*'
    ConstraintDescription: 'The length should be between 6 and 30, must contain only lowercase alphabets.'
  Environment:
    Default: devl
    Description: 'The Environment Name.'
    Type: String
    AllowedValues: ['devl', 'test', 'prod']
    ConstraintDescription: 'The Environment must be devl / test or prod'
 #################################### GitHub Attributes #########################################
  GitHubRef:
    Default: ref_name
    Description: "GitHub Ref Name"
    Type: String
  GitHubURL:
    Default: "https://github.com/"
    Description: "GitHub URL"
    Type: String
  GitHubWFRunNumber:
    Default: 1
    Description: "The Workfloww Run Number."
    Type: Number
  GitHubSHA:
    Default: "sha"
    Description: "The sha value of the last commit"
    Type: String
  GitHubRepository:
    Default: 001-repository
    Description: "The GitHub Repository name."
    Type: String
    MinLength: 10
    MaxLength: 30
    AllowedPattern: "[a-z0-9-.]*"
    ConstraintDescription: "The reposiroty length should be between 10 and 30, must contain only lowercase letter,numbers,dash, dot and should start with a letter."
  CiBuild:
    Default: ""
    Description: "Ci Build of the feature branch."
    Type: String
Resources:
  ConfigRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub '${ProjectName}-ssm-automation-role-${Environment}${CiBuild}'
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            Service:
            - ssm.amazonaws.com
          Action:
          - sts:AssumeRole
      ManagedPolicyArns:
      - arn:aws:iam::aws:policy/service-role/AmazonSSMAutomationRole
      Policies:
      - PolicyName: !Sub '${ProjectName}-ssm-automation-policy-${Environment}${CiBuild}'
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
          - Sid: AllowRevokeSecurityGroupIngress
            Effect: Allow
            Action: 
              - ec2:RevokeSecurityGroupIngress
            Resource: '*'
      Tags: 
      - Key: ProjectName
        Value: !Ref ProjectName
      - Key: EnvironmentName
        Value: !Ref Environment
      - Key: GitHubRepository
        Value: !Ref GitHubRepository
      - Key: GitHubRef
        Value: !Ref GitHubRef
      - Key: GitHubURL
        Value: !Ref GitHubURL
      - Key: GitHubWFRunNumber
        Value: !Ref GitHubWFRunNumber
      - Key: GitHubSHA
        Value: !Ref GitHubSHA
Outputs:
  ConfigRoleArn:
    Description: The Arn of the Config Role
    Value: !GetAtt ConfigRole.Arn
