AWSTemplateFormatVersion: '2010-09-09'
Description: >-
   Project Helenium: CFN Template to create a security group for a webser in a VPC

Metadata:
  TemplateName: webserver-sg-stack.yaml
  TemplateType: Security Group to allow SSH and HTTP traffic.
  Version: 1.0.0
  Owner: Subhamay Bhattacharyya
  ProjectName: Helenium
  Last Modified: Dec 24, 2023
  Resources: 
    - One Security Group with two rules.
    - 1) SSH traffic from anywhere
  StepsToTest: |
    Manualy verify the Stack.
  StepsToCleanup: |
    Stack delete command

  AWS::CloudFormation::Interface:
    ParameterGroups:
    #################################### Project Name and Environment ##############################
    - Label:
        default: "Project Name And Environment:"
      Parameters:
      - ProjectName
      - Environment
    #################################### GitHub Attributes #########################################
    - Label:
        default: "GitHub Attributes:"
      Parameters:
      - GitHubRef
      - GitHubURL
      - GitHubWFRunNumber
      - GitHubSHA
      - GitHubRepository
      - CiBuild
    #################################### Security Group ############################################
    - Label:
        default: "Security Group Parameters"
      Parameters: 
      - VPCId
      - SecurityGroupName
      - SecurityGroupDescription
    ParameterLabels:
      ################################## Project Name and Environment ##############################
      ProjectName:
        default: "Project Name."
      Environment:
        default: "Environment Name."
      ################################## GitHub Attributes #########################################
      GitHubRef:
        default: "GitHub Ref."
      GitHubURL:
        default: "GitHub URL."
      GitHubWFRunNumber:
        default: "GitHub Workflow Run Number."
      GitHubSHA:
        default: "GitHub SHA"
      GitHubRepository:
        default: "GitHub Repository."
      CiBuild:
        default: "Ci Build."
      ################################## Security Group ############################################
      VPCId:
        default: "VPC Id where the security group needs to be created."
      SecurityGroupName: 
        default: "Security Group name."
      SecurityGroupDescription: 
        default: "Security Group description."
Parameters:
  ###################################### Project Name and Environment ##############################
  ProjectName:
    Default: helenium
    Description: "The Project Name for which the custom resource will be used."
    Type: String
    MinLength: 5
    MaxLength: 20
    AllowedPattern: "[a-z]*"
    ConstraintDescription: "The length should be between 5 and 30, must contain only lowercase alphabets."
  Environment:
    Default: devl
    Description: "The Environment Name."
    Type: String
    AllowedValues: ["devl", "test", "prod"]
    ConstraintDescription: "The Environment must be devl / test or prod"
  ###################################### GitHub Attributes #########################################
  GitHubRef:
    Default: ref_name
    Description: "GitHub Ref Name"
    Type: String
  GitHubURL:
    Default: "https://github.com/"
    Description: "GitHub URL"
    Type: String
  GitHubWFRunNumber:
    Default: 1
    Description: "The Workfloww Run Number."
    Type: Number
  GitHubSHA:
    Default: "sha"
    Description: "The sha value of the last commit"
    Type: String
  GitHubRepository:
    Default: 001-tarius
    Description: "The GitHub Repository name."
    Type: String
    MinLength: 10
    MaxLength: 30
    AllowedPattern: "[a-z0-9-.]*"
    ConstraintDescription: "The reposiroty length should be between 10 and 30, must contain only lowercase letter,numbers,dash, dot and should start with a letter."
  CiBuild:
    Default: ""
    Description: "Ci Build of the feature branch."
    Type: String
  ###################################### Security Group ############################################
  VPCId: 
    Description: The VPC Id where the security group will be created.
    Type: AWS::EC2::VPC::Id
  SecurityGroupName:
    Type: String
    Description: The Name of the WebServer security group.
    MinLength: 5
    MaxLength: 8
    AllowedPattern: "[a-zA-Z0-9-]*"
    ConstraintDescription: The length should be between 5 and 8, must contain only alphanumeric character and start with a uppercase letter.
  SecurityGroupDescription:
    Type: String
    Default: "Security Group to allow SSH from anywhere."
    Description: The Security group description.
    AllowedPattern: "[a-zA-Z0-9-. ]*"
    MinLength: 15
    MaxLength: 50
    ConstraintDescription: The length should be between 10 and 50, must contain only alphanumeric character and dot, space or dash and start with an uppercase letter.
Resources:
  SecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: !Sub '${ProjectName}-${SecurityGroupName}${CiBuild}'
      GroupDescription: !Ref SecurityGroupDescription
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: '22'
          ToPort: '22'
          CidrIp: 0.0.0.0/0
          Description: "Allow SSH from anywhere"
        - IpProtocol: tcp
          FromPort: '22'
          ToPort: '22'
          CidrIp: 18.206.107.24/29   ### https://ip-ranges.amazonaws.com/ip-ranges.json
          Description: "Allow SSH from 18.206.107.24/29"
      VpcId: !Ref VPCId
      Tags:
        - Key: Name
          Value: !Sub '${ProjectName}-sg'
        - Key: ProjectName
          Value: !Ref ProjectName
        - Key: Environment
          Value: !Ref Environment
        - Key: GitHubRepository
          Value: !Ref GitHubRepository
        - Key: GitHubRef
          Value: !Ref GitHubRef
        - Key: GitHubURL
          Value: !Ref GitHubURL
        - Key: GitHubWFRunNumber
          Value: !Ref GitHubWFRunNumber
        - Key: GitHubSHA
          Value: !Ref GitHubSHA
Outputs:
  SecurityGroupId:
    Description: Security Group Id
    Value: !Ref SecurityGroup